/**
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * @author Liang-yu
 *
 */
public class Find_the_Difference_389 {
	public static char findTheDifference(String s, String t) {
		int freq[] = new int[26];
		for (int i = 0; i < t.length(); i++)
			freq[t.charAt(i) - 'a']++;
		for (int i = 0; i < s.length(); i++)
			freq[s.charAt(i) - 'a']--;
		for(int i = 0; i < freq.length; i++)
			if(freq[i] == 1)
				return (char) (i+'a');
		return (Character) null;
	}
	
	// online solution
	public char findTheDifference2(String s, String t) {
        int charCode = t.charAt(s.length());
        // Iterate through both strings and char codes
        for (int i = 0; i < s.length(); ++i) {
              charCode -= (int)s.charAt(i);
              charCode += (int)t.charAt(i); 
        }
        return (char)charCode;
    }
	
	
	public static void main(String[] args) {
		char out = findTheDifference("ab","acb");
		System.out.println(out);
	}
}
